# ogl-samples
# http://www.opengl.org/sdk/docs/tutorials/OGLSamples/
#
# name  cwd  command  args  ...
ogl-210-buffer-type	build	release/ogl-210-buffer-type
ogl-210-buffer-update	build	release/ogl-210-buffer-update
ogl-210-draw-elements	build	release/ogl-210-draw-elements
ogl-210-draw-range	build	release/ogl-210-draw-range
ogl-210-query-occlusion	build	release/ogl-210-query-occlusion
ogl-210-rasterizer-viewport	build	release/ogl-210-rasterizer-viewport
ogl-210-sampler-anisotropy-ext	build	release/ogl-210-sampler-anisotropy-ext
ogl-210-sampler-filter	build	release/ogl-210-sampler-filter
ogl-210-sampler-wrap	build	release/ogl-210-sampler-wrap
ogl-210-test-scissor	build	release/ogl-210-test-scissor
ogl-210-texture-2d	build	release/ogl-210-texture-2d
ogl-210-texture-compressed-ext	build	release/ogl-210-texture-compressed-ext
ogl-300-fbo-multisample	build	release/ogl-300-fbo-multisample
ogl-300-test-alpha	build	release/ogl-300-test-alpha
ogl-330-blend-index	build	release/ogl-330-blend-index
ogl-330-blend-rtt	build	release/ogl-330-blend-rtt
ogl-330-buffer-type	build	release/ogl-330-buffer-type
ogl-330-buffer-uniform	build	release/ogl-330-buffer-uniform
ogl-330-buffer-uniform-shared	build	release/ogl-330-buffer-uniform-shared
ogl-330-buffer-update	build	release/ogl-330-buffer-update
ogl-330-draw-instanced	build	release/ogl-330-draw-instanced
ogl-330-draw-instanced-array	build	release/ogl-330-draw-instanced-array
ogl-330-draw-instanced-array-dsa-gtc	build	release/ogl-330-draw-instanced-array-dsa-gtc
ogl-330-draw-multiple	build	release/ogl-330-draw-multiple
ogl-330-error-sampler-gather	build	release/ogl-330-error-sampler-gather
ogl-330-error-sampler-offset	build	release/ogl-330-error-sampler-offset
ogl-330-error-vao	build	release/ogl-330-error-vao
ogl-330-fbo-blit	build	release/ogl-330-fbo-blit
ogl-330-fbo-layered	build	release/ogl-330-fbo-layered
ogl-330-fbo-mipmaps	build	release/ogl-330-fbo-mipmaps
ogl-330-fbo-multisample	build	release/ogl-330-fbo-multisample
ogl-330-fbo-multisample-custom-resolve	build	release/ogl-330-fbo-multisample-custom-resolve
ogl-330-fbo-rtt	build	release/ogl-330-fbo-rtt
ogl-330-fbo-rtt-texture-array	build	release/ogl-330-fbo-rtt-texture-array
ogl-330-fbo-srgb	build	release/ogl-330-fbo-srgb
ogl-330-glsl-discard	build	release/ogl-330-glsl-discard
ogl-330-primitive-flat-shading	build	release/ogl-330-primitive-flat-shading
ogl-330-primitive-smooth-shading	build	release/ogl-330-primitive-smooth-shading
ogl-330-query-conditional	build	release/ogl-330-query-conditional
ogl-330-query-occlusion	build	release/ogl-330-query-occlusion
ogl-330-query-timer	build	release/ogl-330-query-timer
ogl-330-rasterizer-viewport	build	release/ogl-330-rasterizer-viewport
ogl-330-sampler-anisotropy-ext	build	release/ogl-330-sampler-anisotropy-ext
ogl-330-sampler-fetch	build	release/ogl-330-sampler-fetch
ogl-330-sampler-filter	build	release/ogl-330-sampler-filter
ogl-330-sampler-object	build	release/ogl-330-sampler-object
ogl-330-sampler-offset	build	release/ogl-330-sampler-offset
ogl-330-sampler-wrap	build	release/ogl-330-sampler-wrap
ogl-330-sync	build	release/ogl-330-sync
ogl-330-test-scissor	build	release/ogl-330-test-scissor
ogl-330-texture-2d	build	release/ogl-330-texture-2d
ogl-330-texture-array	build	release/ogl-330-texture-array
ogl-330-texture-buffer	build	release/ogl-330-texture-buffer
ogl-330-texture-compressed-ext	build	release/ogl-330-texture-compressed-ext
ogl-330-texture-cube	build	release/ogl-330-texture-cube
ogl-330-texture-rect	build	release/ogl-330-texture-rect
ogl-330-texture-streaming	build	release/ogl-330-texture-streaming
ogl-330-texture-swizzle	build	release/ogl-330-texture-swizzle
ogl-330-transform-feedback	build	release/ogl-330-transform-feedback
ogl-400-blend-rtt	build	release/ogl-400-blend-rtt
ogl-400-buffer-uniform	build	release/ogl-400-buffer-uniform
ogl-400-buffer-uniform-shared-gtc	build	release/ogl-400-buffer-uniform-shared-gtc
ogl-400-draw-indirect	build	release/ogl-400-draw-indirect
ogl-400-error-sampler-fetch	build	release/ogl-400-error-sampler-fetch
ogl-400-fbo-layered	build	release/ogl-400-fbo-layered
ogl-400-fbo-multisample	build	release/ogl-400-fbo-multisample
ogl-400-fbo-rtt	build	release/ogl-400-fbo-rtt
ogl-400-fbo-rtt-texture-array	build	release/ogl-400-fbo-rtt-texture-array
ogl-400-primitive-instanced	build	release/ogl-400-primitive-instanced
ogl-400-primitive-smooth-shading	build	release/ogl-400-primitive-smooth-shading
ogl-400-primitive-tessellation	build	release/ogl-400-primitive-tessellation
ogl-400-program-64	build	release/ogl-400-program-64
ogl-400-program-subroutine	build	release/ogl-400-program-subroutine
ogl-400-program-varying-blocks	build	release/ogl-400-program-varying-blocks
ogl-400-program-varying-structs	build	release/ogl-400-program-varying-structs
ogl-400-sampler-array	build	release/ogl-400-sampler-array
ogl-400-sampler-array-gtc	build	release/ogl-400-sampler-array-gtc
ogl-400-sampler-fetch	build	release/ogl-400-sampler-fetch
ogl-400-sampler-gather	build	release/ogl-400-sampler-gather
ogl-400-texture-buffer-rgb	build	release/ogl-400-texture-buffer-rgb
ogl-400-texture-compressed-arb	build	release/ogl-400-texture-compressed-arb
ogl-400-transform-feedback-object	build	release/ogl-400-transform-feedback-object
ogl-410-debug-output-arb	build	release/ogl-410-debug-output-arb
ogl-410-fbo-layered	build	release/ogl-410-fbo-layered
ogl-410-fbo-multisample-dsa-ext	build	release/ogl-410-fbo-multisample-dsa-ext
ogl-410-fbo-multisample-dsa-gtc	build	release/ogl-410-fbo-multisample-dsa-gtc
ogl-410-fbo-multisample-position-amd	build	release/ogl-410-fbo-multisample-position-amd
ogl-410-fbo-rtt-dsa-ext	build	release/ogl-410-fbo-rtt-dsa-ext
ogl-410-primitive-bindless-nv	build	release/ogl-410-primitive-bindless-nv
ogl-410-primitive-instanced	build	release/ogl-410-primitive-instanced
ogl-410-primitive-tessellation-2	build	release/ogl-410-primitive-tessellation-2
ogl-410-primitive-tessellation-5	build	release/ogl-410-primitive-tessellation-5
ogl-410-program-64	build	release/ogl-410-program-64
ogl-410-program-binary	build	release/ogl-410-program-binary
ogl-410-program-separate-dsa-gtc	build	release/ogl-410-program-separate-dsa-gtc
ogl-410-program-varying-gtc	build	release/ogl-410-program-varying-gtc
ogl-410-sampler-fetch-dsa-ext	build	release/ogl-410-sampler-fetch-dsa-ext
ogl-410-texture-barrier-nv	build	release/ogl-410-texture-barrier-nv
ogl-410-texture-copy-nv	build	release/ogl-410-texture-copy-nv
ogl-410-texture-image-ext	build	release/ogl-410-texture-image-ext
